### ISSUE TITLE
Not compatible with wagtail 2.7

### ISSUE THREAD

**Issue by abhijith-kefi** [isotoma/wagtailtinymce#28]
I am getting following error
`Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kefi/Work/kannur-new/env/lib/python3.6/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/home/kefi/Work/kannur-new/env/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "/home/kefi/Work/kannur-new/env/lib/python3.6/site-packages/django/core/management/base.py", line 390, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/kefi/Work/kannur-new/env/lib/python3.6/site-packages/django/core/management/base.py", line 377, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/kefi/Work/kannur-new/env/lib/python3.6/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/kefi/Work/kannur-new/env/lib/python3.6/site-packages/wagtail/admin/checks.py", line 63, in get_form_class_check
    if not issubclass(edit_handler.get_form_class(), WagtailAdminPageForm):
  File "/home/kefi/Work/kannur-new/env/lib/python3.6/site-packages/wagtail/admin/edit_handlers.py", line 354, in get_form_class
    widgets=self.widget_overrides())
  File "/home/kefi/Work/kannur-new/env/lib/python3.6/site-packages/wagtail/admin/edit_handlers.py", line 61, in get_form_for_model
    return metaclass(class_name, (form_class,), form_class_attrs)
  File "/home/kefi/Work/kannur-new/env/lib/python3.6/site-packages/wagtail/admin/forms/models.py", line 66, in __new__
    new_class = super(WagtailAdminModelFormMetaclass, cls).__new__(cls, name, bases, attrs)
  File "/home/kefi/Work/kannur-new/env/lib/python3.6/site-packages/modelcluster/forms.py", line 233, in __new__
    new_class = super(ClusterFormMetaclass, cls).__new__(cls, name, bases, attrs)
  File "/home/kefi/Work/kannur-new/env/lib/python3.6/site-packages/django/forms/models.py", line 256, in __new__
    apply_limit_choices_to=False,
  File "/home/kefi/Work/kannur-new/env/lib/python3.6/site-packages/django/forms/models.py", line 176, in fields_for_model
    formfield = formfield_callback(f, **kwargs)
  File "/home/kefi/Work/kannur-new/env/lib/python3.6/site-packages/wagtail/admin/forms/models.py", line 47, in formfield_for_dbfield
    return db_field.formfield(**kwargs)
  File "/home/kefi/Work/kannur-new/env/lib/python3.6/site-packages/wagtail/core/fields.py", line 18, in formfield
    defaults = {'widget': get_rich_text_editor_widget(self.editor, features=self.features)}
  File "/home/kefi/Work/kannur-new/env/lib/python3.6/site-packages/wagtail/admin/rich_text/__init__.py", line 27, in get_rich_text_editor_widget
    cls = import_string(editor['WIDGET'])
  File "/home/kefi/Work/kannur-new/env/lib/python3.6/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kefi/Work/kannur-new/env/lib/python3.6/site-packages/wagtailtinymce/rich_text.py", line 33, in <module>
    from wagtail.wagtailadmin.edit_handlers import RichTextFieldPanel
ModuleNotFoundError: No module named 'wagtail.wagtailadmin'`

Django version : 2.2.4
Wagtail version : 2.7
Python Version:3.6.9

**Comment by xavitorne** [comment]
Try this fork:
https://github.com/Junatum/wagtailtinymce/tree/custom-1.2
